alias: Fast Update Sensors
description: Fast Update Sensors
trigger:
  - platform: time_pattern
    seconds: /3
condition: []
action:
  - service: homeassistant.update_entity
    target:
      entity_id:
        - sensor.tmp_grid_power
        - sensor.solarpv_power_b
    data: {}
mode: single